# Cas13 Guide Design - RLTR6 custom configuration
# Uses standard FASTA transcriptome for off-target search.

project_name: "cas13_guides"

species_options:
  mouse:
    ensembl_name: "mus_musculus"
    reference_transcriptome: "resources/reference/gencode.vM37.transcripts.fa"
  human:
    ensembl_name: "homo_sapiens"
    reference_transcriptome: "resources/reference/gencode.v47.transcripts.fa"

tiger:
  model_path: "resources/models/tiger_model"
  calibration_params: "resources/models/tiger_model/calibration_params.pkl"
  scoring_params: "resources/models/tiger_model/scoring_params.pkl"
  batch_size: 500
  guide_length: 23
  context_5p: 3
  context_3p: 0

offtarget:
  max_mismatches: 5
  binary_path: "bin/offtarget_search"
  chunk_size: 5000
  min_score_for_offtarget: 0.7

filtering:
  top_n_guides: 10
  min_guide_score: 0.80
  mm1_threshold: 0
  mm2_threshold: 0
  adaptive_mm0: true
  mm0_tolerance: 3

slurm:
  account: "sanjana"
  partition: "cpu"
  time: "16:00:00"
  mem: "200G"
  cpus_per_task: 8

ensembl:
  rest_url: "https://rest.ensembl.org"
  prefer_canonical: true
  prefer_appris_principal: true
  rate_limit_delay: 0.5

output:
  save_intermediate: true
  compress_logs: false
  generate_plots: true
  validate_mm0_locations: true

compute:
  threads: 64
  memory_gb: 200
  use_gpu: false
